# Generated by Django 3.2.4 on 2021-08-25 03:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_id', models.CharField(max_length=1000, null=True)),
                ('scenario_id', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000, null=True)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('case_count', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
