# Generated by Django 3.2.4 on 2021-09-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210903_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='department_id',
        ),
    ]
