# Generated by Django 3.2.4 on 2021-09-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_detail_scenario_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='element_click_id',
            new_name='element_id',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='element_input',
            new_name='element_value',
        ),
        migrations.RemoveField(
            model_name='case',
            name='element_xpath',
        ),
    ]
