# Generated by Django 3.2.4 on 2021-09-24 05:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210922_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=1000, null=True)),
                ('device_version', models.CharField(max_length=1000, null=True)),
                ('platform_version', models.CharField(max_length=1000, null=True)),
                ('app_name', models.CharField(max_length=1000, null=True)),
                ('app_activity', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
