# Generated by Django 3.2.4 on 2021-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='main',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
