# Generated by Django 3.2.4 on 2021-09-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210924_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='main',
        ),
        migrations.AddField(
            model_name='device',
            name='app_file_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='app_version',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
