# Generated by Django 3.2.4 on 2021-09-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20210927_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_version',
            new_name='device_os',
        ),
    ]
