# Generated by Django 3.2.4 on 2021-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_rename_device_version_device_device_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='use_yn',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
