# Generated by Django 3.2.4 on 2021-09-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_scenario_use_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='case_count',
        ),
    ]
